version: "3"
networks:
  1panel-network:
    external: true
services:
  gotutu:
    container_name: openlist-bed
    image: gmeroo/openlist-bed:latest
    ports:
      - "3205:6001"
    networks:
      - 1panel-network
    restart: on-failure
    environment:
      - API_KEY=apiKey
      - HOST=http://localhost:3205
      - OPENLIST_HOST=http://openlist:3200
      - OPENLIST_TOKEN=openlistToken
      - OPENLIST_PATH=onedrive/img
      - AUTO_WEBP=false
